### PR TITLE
3 domaca zadaca

### PR DESCRIPTION
**Pull request by lihter**

### CODE REVIEW

**Comment by lihter** [comment]
Osim zadataka iz 3. domaće zadaće, vidljivu promijenu u kodu ostvario sam i kod implementacije tema/stilova s potpuno novim pristupom s obzirom na prošle zadaće.

**Comment by istaudacher** [comment]
@lihter Could you please merge 2-domaca-zadaca into master so that I can see what has changed between 2-domaca-zadaca and this branch? Thanks!

**Comment by lihter** [comment]
Screenshot 2021-05-18 at 21 26 59
I'm not sure if I solved the problem, but now it says that it's merged. Let me know if it's still not properly merged :)

**Review by istaudacher — COMMENTED** [review]
Very good!
I see that you had a problem with Reachability, you could read this example https://itnext.io/handling-reachability-in-swift-d12dbd538df and try to implement it. There are many more examples on the net.

**Pull request merged**
